FROM python:3.8

ARG API_TOKEN

ARG WEBHOOK_ENABLED
ARG WEBHOOK_HOST
ARG WEBHOOK_PORT
ARG WEBHOOK_PATH

ARG WEBAPP_HOST
ARG WEBAPP_PORT

ARG DEV_LINK
ARG REPO_LINK

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV ENV_API_TOKEN=$API_TOKEN

ENV ENV_WEBHOOK_ENABLED=$WEBHOOK_ENABLED
ENV ENV_WEBHOOK_HOST=$WEBHOOK_HOST
ENV ENV_WEBHOOK_PORT=$WEBHOOK_PORT
ENV ENV_WEBHOOK_PATH=$WEBHOOK_PATH

ENV ENV_WEBAPP_HOST=$WEBAPP_HOST
ENV ENV_WEBAPP_PORT=$WEBAPP_PORT

ENV ENV_DEV_LINK=$DEV_LINK
ENV ENV_REPO_LINK=$REPO_LINK

CMD [ "python", "bot.py" ]
